# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='memo',
            name='images',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='memo',
            name='tasks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
